---
title: Farwalker3's Blog
tagline: A personal blog and portfolio
description: Personal blog and portfolio site
url: "https://farwalker3.github.io"
baseurl: ""  # Empty for username.github.io sites

github:
  username: farwalker3
social:
  name: John C. Barr
  email: # your-email@example.com
  links:
    - https://github.com/farwalker3

theme: jekyll-theme-chirpy
lang: en
timezone: UTC

# Collections
collections:
  posts:
    title: Posts
    output: true
  tabs:
    title: Tabs
    output: true
    sort_by: order

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: true
      toc: true
      permalink: "/posts/:title/"
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs
    values:
      layout: page
      permalink: "/:title/"
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true

# Theme settings
toc: true
comments:
  active: # disqus, utterances, giscus

# Assets
assets:
  self_host:
    enabled: false

# PWA
pwa:
  enabled: false

# Pagination
paginate: 10

# Build settings
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs:
      - development

exclude:
  - "*.gem"
  - "*.gemspec"
  - docs
  - tools
  - README.md
  - LICENSE
  - rollup.config.js
  - package*.json

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: "/tags/:name/"
    category: "/categories/:name/"